DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year VARCHAR(4) NOT NULL,
  title VARCHAR(250) NOT NULL,
  studios VARCHAR(250) DEFAULT NULL,
  producers VARCHAR(250) DEFAULT NULL,
  winner BOOLEAN
);